spring.application.name=studentapp

# DB
spring.datasource.url=jdbc:sqlite:Student-APP-Database.db
# C:/1VGTech-Sep2025/1VSSWorkspace-23Jan2026/MySQLiteDatabase.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true

# JWT
app.jwt.secret=change_this_secret_in_prod
app.jwt.expiration-ms=3600000

# React forwarding
spring.web.resources.add-mappings=true
server.port=8080

